name: RokiDivineProtection
main: com.royalkingdoms.rokidivineprotection.RokiDivineProtection
version: 1.0
api: ["1.1.0"]
author: YoussGm3o8
description: Divine Land Protection Plugin
depend: 
  - EconomyAPI
commands:
  protectland:
    description: Claim and protect a chunk of land
    usage: /protectland
  unprotectland:
    description: Unclaim a chunk of land, there will be no refund
    usage: /unprotectland
  findprotectedchunks:
    description: Lists all the protected chunks owned by the player.
    usage: /findprotectedchunks